# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Brian Lovell's Awesome fastai Blog
description: Feel free to follow my AI journey with fastai.
github_username: lovellbrian

# Email and twitter are optional:
email: lovell@itee.uq.edu.au
twitter_username: LovellProf

# Set Time.zone to the time zone name of your choice, e.g. `America/New_York`. 
# Otherwise posts may not appear until that time has passed in the default time zone. 
# Note that you can schedule posts in the future in any time zone by changing the post's file name date prefix. 
# For example, to schedule a post for 2023-05-05 08:00:00 UTC, name the file 2023-05-05-08-00-00-future-post.md with the following YAML front matter.
time_zone: Australia/Brisbane

# Set baseurl to help display pdfs with {{ site.baseurl }}
baseurl: /lovellbrian.github.io

# Set this to true to get LaTeX math equation support 
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
